services:
  sapphire-portfolio:
    build:
      context: ./sapphire-portfolio
      dockerfile: Dockerfile
    ports:
      - "3003:3003"
    networks:
      - backend

  sapphire-relayer:
    build:
      context: ./sapphire-relayer
      dockerfile: Dockerfile
    ports:
      - "3002:3002"
    networks:
      - backend

  wallet-factory:
    build:
      context: ./wallet-factory
      dockerfile: Dockerfile
    ports:
      - "3001:3001"
    networks:
        - backend

  api-gateway:
    build:
      context: ./api-gateway
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    networks:
        - backend

networks:
    backend:
